# Registration Controller
user_registration:
    path:       /register
    defaults:   { _controller: UserBundle:Registration:register }


# Security Controller
login:
    path:       /login
    defaults:   { _controller: UserBundle:Security:login }

main:
    path:       /test
    defaults:   { _controller: UserBundle:Security:main }
