# Registration Controller
user_registration:
    path:       /register
    defaults:   { _controller: UserBundle:Registration:register }


# Security Controller
login:
    path:       /login
    defaults:   { _controller: UserBundle:Security:login }

login_check:
    path:       /login_check

main:
    path:       /main
    defaults:   { _controller: UserBundle:Security:main }
